"""Convert real-world geodata to an OpenTTD scenario town_data JSON.

Pulls cities/towns from OpenStreetMap via Overpass API (free, no key) for a
lat/lon bounding box and emits the JSON shape OpenTTD's Scenario Editor
loads:

    [
      {"name": "London", "population": 44910, "city": true,
       "x": 0.7998, "y": 0.7090}
    ]

Conventions (from OpenTTD wiki "Importing Town Data"):
  * x, y are normalized 0-1 fractions of map dimensions
  * OpenTTD's coordinate system is rotated vs image editors; the docs
    instruct a final X/Y swap before writing - we apply it by default
    and expose `--no-swap` for users testing alignment.

Usage:

    python3 -m agent.sandbox.geo \\
        --bbox 51.28,-0.510,51.69,0.334 \\
        --out  scenario/london \\
        --name London

Heightmap: NOT generated by this tool. Mapbox terrain-rgb is the easiest
upstream (needs MAPBOX_TOKEN); see the comment block at the bottom for the
shape of that integration if/when we want to add it.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import List, Optional, Tuple

try:
    import httpx
except ImportError:
    httpx = None  # type: ignore


# Public Overpass mirrors. We try them in order. Be polite: this is the
# common community resource. Don't bulk-scrape.
OVERPASS_ENDPOINTS = (
    "https://overpass-api.de/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter",
    "https://overpass.openstreetmap.fr/api/interpreter",
)


@dataclass
class Town:
    name: str
    lat: float
    lon: float
    population: int
    city: bool


# ---------------------------------------------------------------------------
# Fetch
# ---------------------------------------------------------------------------

def fetch_osm_towns(bbox: Tuple[float, float, float, float],
                     min_pop: int = 500,
                     timeout_s: float = 90.0,
                     include_villages: bool = False) -> List[Town]:
    """bbox = (lat_south, lon_west, lat_north, lon_east).

    Returns nodes tagged place=city|town (and village if include_villages).
    Drops nodes without a name. Falls back to 0 population when missing.
    """
    if httpx is None:
        raise RuntimeError("httpx required: pip3 install --user httpx")
    s, w, n, e = bbox
    if not (-90 <= s <= n <= 90 and -180 <= w <= e <= 180):
        raise ValueError(f"bad bbox {bbox}")
    places = "city|town" + ("|village" if include_villages else "")
    query = (
        f"[out:json][timeout:{int(timeout_s)}];\n"
        f"( node[\"place\"~\"^({places})$\"][\"name\"]"
        f"({s},{w},{n},{e}); );\n"
        "out;"
    )
    # Overpass community asks for a descriptive User-Agent so they can
    # contact operators about problem traffic. Use one.
    headers = {
        "User-Agent": "agent-openttd-arena/0.1 (github.com/agent-openttd-arena)",
    }
    last_err = None
    for url in OVERPASS_ENDPOINTS:
        try:
            r = httpx.post(url, data={"data": query},
                            headers=headers, timeout=timeout_s)
            r.raise_for_status()
            data = r.json()
            return _parse_overpass(data, min_pop)
        except Exception as ex:
            last_err = ex
            continue
    raise RuntimeError(f"all Overpass endpoints failed; last: {last_err}")


def _ascii_name(tags: dict) -> str:
    """Pick the best ASCII-renderable name from OSM tags.

    OpenTTD's default font has Latin only - Arabic/Cyrillic/CJK names
    render as garbage glyphs. Worse: OpenTTD's LoadTownData *segfaults*
    on names longer than ~31 chars (fixed-size buffer). We:
      1. prefer name:en, then int_name, then unidecode(native)
      2. take only the first comma/slash/semicolon-separated variant
         (OSM sometimes packs multiple spellings into one tag)
      3. truncate to 30 chars to stay safely under the buffer limit
    """
    if not tags:
        return ""
    candidates = [
        tags.get("name:en"),
        tags.get("int_name"),
    ]
    # Any other en variant (rare but cheap to scan)
    for k, v in tags.items():
        if k.startswith("name:en") and v and v not in candidates:
            candidates.append(v)
    # Native name if it's already ASCII
    native = tags.get("name") or ""
    if native and all(ord(c) < 128 for c in native):
        candidates.append(native)
    chosen = ""
    for c in candidates:
        if c and c.strip():
            chosen = c
            break
    # Last resort: transliterate the native script.
    if not chosen and native:
        try:
            from unidecode import unidecode
            t = unidecode(native).strip()
            if t:
                chosen = t
        except ImportError:
            chosen = native  # garbage but at least set
    return _safe_town_name(chosen)


def _safe_town_name(name: str) -> str:
    """Sanitize a town name for OpenTTD's LoadTownData: take first variant,
    strip punctuation that has crashed OpenTTD's town-name parser, truncate
    to 30 chars.

    OpenTTD 15.3 LoadTownData segfaults on names containing apostrophes and
    other non-alphanumeric punctuation; observed in 2026-04-26 testing on
    Syria scenarios. We keep the safe set: letters, digits, space, hyphen.
    """
    if not name:
        return ""
    # If OSM packed alternatives (e.g. "Maharda, Mharda, Mhardeh"), keep first.
    for sep in (",", "/", ";", " - ", " | ", " (", "—", "–"):
        if sep in name:
            name = name.split(sep, 1)[0]
    # Drop apostrophes/quotes/parens/brackets/colons/dots that have crashed
    # the parser. Keep letters, digits, space, hyphen.
    drop = set("'`\"()[]{}<>:!?*&^%$#@~|\\.")
    name = "".join(c for c in name if c not in drop)
    # Collapse runs of whitespace.
    name = " ".join(name.split())
    if len(name) > 30:
        if " " in name[:30]:
            name = name[:30].rsplit(" ", 1)[0]
        else:
            name = name[:30]
    return name.strip()


def _parse_overpass(data: dict, min_pop: int) -> List[Town]:
    out: List[Town] = []
    for el in data.get("elements", []):
        if el.get("type") != "node":
            continue
        tags = el.get("tags") or {}
        name = _ascii_name(tags)
        if not name:
            continue
        place = tags.get("place", "")
        try:
            pop = int(tags.get("population") or 0)
        except (TypeError, ValueError):
            pop = 0
        if pop < min_pop and place != "city":
            # Cities without a population tag still pass.
            if pop == 0 and place == "city":
                pass
            else:
                continue
        out.append(Town(
            name=name,
            lat=float(el["lat"]),
            lon=float(el["lon"]),
            population=pop,
            city=(place == "city"),
        ))
    return out


# ---------------------------------------------------------------------------
# Convert
# ---------------------------------------------------------------------------

def to_ottd_json(towns: List[Town],
                  bbox: Tuple[float, float, float, float],
                  swap_xy: bool = True,
                  pop_scale: float = 1.0 / 100.0,
                  pop_floor: int = 200,
                  pop_cap: int = 50000) -> List[dict]:
    """Project (lat, lon) onto normalized image coords, then optionally
    apply OpenTTD's X/Y swap. Population is scaled by `pop_scale` and
    clamped into [pop_floor, pop_cap] (real cities are too big to import
    one-to-one)."""
    s, w, n, e = bbox
    lat_span = n - s
    lon_span = e - w
    if lat_span <= 0 or lon_span <= 0:
        raise ValueError("degenerate bbox")
    out: List[dict] = []
    for t in towns:
        # image coords: x increases east, y increases south.
        x_img = (t.lon - w) / lon_span
        y_img = (n - t.lat) / lat_span
        if not (0.0 <= x_img <= 1.0 and 0.0 <= y_img <= 1.0):
            continue
        # OpenTTD expects swapped X/Y when imported alongside a
        # north-up heightmap, per the wiki docs.
        if swap_xy:
            x_out, y_out = y_img, x_img
        else:
            x_out, y_out = x_img, y_img
        scaled_pop = int(t.population * pop_scale)
        scaled_pop = max(pop_floor, min(pop_cap, scaled_pop or pop_floor))
        out.append({
            "name": t.name,
            "population": scaled_pop,         # OpenTTD target
            "real_population": int(t.population),  # actual OSM value (for ExpandTown sizing in GS)
            "city": bool(t.city),
            "x": round(x_out, 6),
            "y": round(y_out, 6),
        })
    # Stable order: cities first, then by population desc, then name.
    out.sort(key=lambda r: (not r["city"], -r["population"], r["name"]))
    return out


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _parse_bbox(s: str) -> Tuple[float, float, float, float]:
    parts = [float(p) for p in s.split(",")]
    if len(parts) != 4:
        raise argparse.ArgumentTypeError("bbox: lat_s,lon_w,lat_n,lon_e")
    return tuple(parts)  # type: ignore[return-value]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--bbox", required=True, type=_parse_bbox,
                    help="lat_south,lon_west,lat_north,lon_east "
                         "(e.g. 51.28,-0.510,51.69,0.334 for London)")
    ap.add_argument("--out", required=True, type=Path,
                    help="output directory (created if missing)")
    ap.add_argument("--name", default="scenario",
                    help="base filename for outputs (default: scenario)")
    ap.add_argument("--min-pop", type=int, default=500)
    ap.add_argument("--include-villages", action="store_true",
                    help="also include place=village (otherwise city|town only)")
    ap.add_argument("--no-swap", action="store_true",
                    help="don't apply OpenTTD's X/Y swap (test alignment first)")
    ap.add_argument("--pop-scale", type=float, default=0.01,
                    help="multiplier on real population (default 0.01)")
    ap.add_argument("--pop-cap", type=int, default=50000)
    args = ap.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)
    print(f"querying Overpass for bbox {args.bbox} ...", file=sys.stderr)
    towns = fetch_osm_towns(args.bbox, min_pop=args.min_pop,
                             include_villages=args.include_villages)
    print(f"  fetched {len(towns)} towns from OSM", file=sys.stderr)

    converted = to_ottd_json(
        towns, args.bbox,
        swap_xy=not args.no_swap,
        pop_scale=args.pop_scale,
        pop_cap=args.pop_cap,
    )
    out_path = args.out / f"{args.name}_towns.json"
    out_path.write_text(json.dumps(converted, indent=2) + "\n")

    raw_path = args.out / f"{args.name}_raw_osm.json"
    raw_path.write_text(json.dumps([asdict(t) for t in towns], indent=2) + "\n")

    print(f"wrote {len(converted)} towns -> {out_path}")
    print(f"raw OSM dump            -> {raw_path}")
    print()
    print("To use in OpenTTD:")
    print(f"  cp {out_path} ~/Documents/OpenTTD/scenario/heightmap/")
    print("  open OpenTTD -> Scenario Editor -> Load heightmap PNG")
    print("  -> Town Generation -> Load from file -> select the JSON")
    return 0


# ---------------------------------------------------------------------------
# Heightmap from Mapbox terrain-rgb (NOT IMPLEMENTED - shape only)
# ---------------------------------------------------------------------------
#
# Once we want a heightmap PNG to ship alongside the towns:
#
#   1. Pick a Mapbox zoom that gives ~1px per OpenTTD tile at output size.
#      For a 1024x1024 OpenTTD map covering ~50km, zoom ~12 works.
#   2. For each (z, x, y) tile in the bbox:
#        url = f"https://api.mapbox.com/v4/mapbox.terrain-rgb/{z}/{x}/{y}.pngraw?access_token={token}"
#        elevation_m = -10000 + ((R*256*256 + G*256 + B) * 0.1)
#   3. Stitch tiles, reproject to OpenTTD's required aspect ratio
#      (1:1, 1:2, 1:4, etc.), resize to one of (256, 512, 1024, 2048)^.
#   4. Normalize elevation to 0-255 grayscale; sea level -> 0.
#
# Free alternative: SRTM via NASA Earthdata (more setup) or open-elevation.com
# (rate-limited). Keep this in mind before promising the feature.

if __name__ == "__main__":
    sys.exit(main())
